### ISSUE TITLE
Alphabet (ACGT) and model number of modified bases (-41) do not agree

### ISSUE THREAD

**Issue by tpesout** [nanoporetech/megalodon#204]
I'm attempting to run megalodon 2.3.5 with guppy 5.0.11 using the `dna_r9.4.1_450bps_modbases_5mc_hac_prom.cfg` configuration:
```
megalodon input_files/ --outputs basecalls mod_mappings mods --reference /path/to/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna --mod-motif m CG 0 --processes 5 --output-directory output/ --guppy-server-path /opt/ont-guppy-cpu_5.0.11/bin/guppy_basecall_server --guppy-config dna_r9.4.1_450bps_modbases_5mc_hac_prom.cfg --guppy-concurrent-reads 5 --guppy-timeout 300
```

..and I get this output:
```
[23:03:18] Running Megalodon version 2.3.5
[23:03:18] Loading guppy basecalling backend
[23:03:19] Loading reference
******************** WARNING: "mods" output requested, so "per_read_mods" will be added to outputs. ********************
[23:04:31] Loaded model calls canonical alphabet ACGT and modified bases m=5mC (alt to C)
Traceback (most recent call last):
  File "/usr/local/bin/megalodon", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.6/dist-packages/megalodon/__main__.py", line 726, in _main
    megalodon._main(args)
  File "/usr/local/lib/python3.6/dist-packages/megalodon/megalodon.py", line 1776, in _main
    args, model_info, ref_out_info, map_info
  File "/usr/local/lib/python3.6/dist-packages/megalodon/megalodon.py", line 1468, in parse_mod_args
    ref_full_path_decode=not args.reference_anchored_index_decode,
  File "/usr/local/lib/python3.6/dist-packages/megalodon/mods.py", line 2217, in __init__
    self.alphabet, model_info.output_size - self.n_can_state - 1
AssertionError: Alphabet (ACGT) and model number of modified bases (-41) do not agree.
```

I did not have this issue with 2.3.4, is it a problem in the new release?  Can I resolve this by changing my guppy version or model file?

-Trevor

**Comment by marcus1487** [comment]
This has been fixed in release 2.4.0

**Comment by uros-sipetic** [comment]
Hey sorry for posting on an old thread, but I'm still seeing this issue with 2.4.1 and with 2.4.2. 
Using `--outputs per_read_mods` does help though. 
I tried installing both with pip, and by downloading the source from github here and then installing it. 
Anything else in particular I should be paying attention to or...?

**Comment by jdemeul** [comment]
I can confirm I'm also still seeing this issue (and the `--outputs per_read_mods` workaround) with the 2.4+ versions of megalodon. Perhaps worth revisiting?

**Comment by organic-chemistry** [comment]
I still se this in the 2.5 version.
Right now the workaround is to install the 2.3.4 version:
```
pip install megalodon==2.3.4
```

**Comment by marcus1487** [comment]
I would highly recommend moving to the new Remora modified base models (see `--remora-modified-bases` argument). Remora modified base models provide higher accuracy modified base calls and allow users to obtain the same canonical basecalls as a run without modified bases being called.
